"""tasks: the background job queue

Revision ID: 150bd8aa1e1a
Revises: 6546d61a3172

Slice B1. One new table, nothing else touched.

The two partial indexes are the point, not decoration: they are the claim query
(`status = 'pending' and scheduled_at <= now() and kind = any(...)`, ordered by
`scheduled_at`) and the stale-reclaim query (`status = 'running' and started_at
<= cutoff`). Partial because a queue table keeps its history, so pending and
running rows are a small and shrinking minority of it -- an index over the whole
table would grow forever to serve a query that only ever wants the tail.

`status` carries a CHECK, as every status column here does. `kind` deliberately
does not: the set of kinds is a code-level registry in `jfl_worker` that grows
with every slice, a kind no deployed worker recognises is simply never claimed,
and a CHECK would cost a migration per handler to buy nothing.

`updated_at` carries `onupdate=func.now()` in tables.py, which is a client-side
SQLAlchemy Core default rather than a database trigger -- there is nothing for
autogenerate to emit for it and nothing is missing below.

No hand edits needed: no `Vector` column (so the usual missing
`import pgvector.sqlalchemy` is moot) and the table is new, so there is no
NOT NULL-on-existing-rows hazard.

Reverses cleanly: downgrade drops only what upgrade added. Dropping the table
discards queued work, which is the correct behaviour for a rollback -- the rows
are transient by nature and every handler is idempotent.
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '150bd8aa1e1a'
down_revision = '6546d61a3172'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('pending','running','succeeded','failed')", name=op.f('ck_tasks_status')),
    sa.CheckConstraint('attempts >= 0 and max_attempts >= 1', name=op.f('ck_tasks_attempt_counts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tasks_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index('ix_tasks_pending_scheduled_at', 'tasks', ['scheduled_at', 'kind'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('ix_tasks_running_started_at', 'tasks', ['started_at'], unique=False, postgresql_where=sa.text("status = 'running'"))
    op.create_index('ix_tasks_user_id_created_at', 'tasks', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_user_id_created_at', table_name='tasks')
    op.drop_index('ix_tasks_running_started_at', table_name='tasks', postgresql_where=sa.text("status = 'running'"))
    op.drop_index('ix_tasks_pending_scheduled_at', table_name='tasks', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('tasks')
    # ### end Alembic commands ###
