"""Profile setup: answers, objectives, ruled-out decisions

Revision ID: 170e706e57bc
Revises: 6b3ce06d7b4e
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '170e706e57bc'
down_revision = '6b3ce06d7b4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_key', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), server_default='', nullable=False),
    sa.Column('structured', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    # clock_timestamp(), not now(): this is append-only history, and now() is
    # transaction-start time -- two answers to the same question saved in one
    # transaction would tie, making "the latest row" ambiguous.
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.CheckConstraint("question_key in ('location_commute','workplace_arrangements','levels','comp_floor','contract_types','notice_period','right_to_work','categorical_no','disciplines','trajectory','employer_deal_breakers','warning_signs')", name=op.f('ck_profile_answers_question_key')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profile_answers_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_answers'))
    )
    op.create_index('ix_profile_answers_user_id_question_key_created_at', 'profile_answers', ['user_id', 'question_key', 'created_at'], unique=False)
    op.create_table('profile_objectives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('objective_text', sa.Text(), server_default='', nullable=False),
    sa.Column('evidence_text', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ordinal between 1 and 4', name=op.f('ck_profile_objectives_ordinal_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profile_objectives_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_objectives')),
    sa.UniqueConstraint('user_id', 'ordinal', name=op.f('uq_profile_objectives_user_id_ordinal'))
    )
    op.create_table('profile_ruled_out',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('decision_text', sa.Text(), nullable=False),
    # clock_timestamp(), same reasoning as profile_answers.created_at above.
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('reopened_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profile_ruled_out_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_ruled_out'))
    )
    op.create_index('ix_profile_ruled_out_user_id_recorded_at', 'profile_ruled_out', ['user_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profile_ruled_out_user_id_recorded_at', table_name='profile_ruled_out')
    op.drop_table('profile_ruled_out')
    op.drop_table('profile_objectives')
    op.drop_index('ix_profile_answers_user_id_question_key_created_at', table_name='profile_answers')
    op.drop_table('profile_answers')
    # ### end Alembic commands ###
