"""board job workplace and locations, saved job filter, board filter exceptions

Revision ID: 9eb127bee328
Revises: 12fd7dd9c2a5

Filtering for watched boards. Boards are still fetched whole; everything here is
a lens over what is stored, so no filter can make a job look as though it
vanished from a board's history.

  * `board_jobs.workplace` (closed set, CHECK), `workplace_label` (the employer's
    own words, verbatim) and `locations` (every listed location). Descriptive
    data refreshed on every sighting, like `requisition_id`. Neither `external_id`
    nor `fingerprint` is touched: existing rows read `unknown` / `{}` until their
    next sighting, and repost detection over existing history is unchanged;
  * `watched_boards.include_unstated_workplace` -- NULL means the platform default;
  * `job_filters` -- one saved filter per user;
  * `board_filter_exceptions` -- per-board "also include" rules with a verbatim note.

Autogenerated; reviewed, no hand edits needed beyond this docstring (no `Vector`
column, so the usual pgvector import is moot). The value lists are written out
as literals, never imported, because a migration is a snapshot. Reverses cleanly;
downgrade discards saved filters and exceptions, which belong to the feature it
removes.
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '9eb127bee328'
down_revision = '12fd7dd9c2a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('job_filters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workplaces', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('title_includes', sa.Text(), server_default='', nullable=False),
    sa.Column('title_excludes', sa.Text(), server_default='', nullable=False),
    sa.Column('location', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("workplaces <@ array['remote','hybrid','onsite','unknown']::text[]", name=op.f('ck_job_filters_workplaces')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_job_filters_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_filters')),
    sa.UniqueConstraint('user_id', name=op.f('uq_job_filters_user_id'))
    )
    op.create_table('board_filter_exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('workplaces', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('location', sa.Text(), server_default='', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("workplaces <@ array['remote','hybrid','onsite','unknown']::text[]", name=op.f('ck_board_filter_exceptions_workplaces')),
    sa.ForeignKeyConstraint(['board_id'], ['watched_boards.id'], name=op.f('fk_board_filter_exceptions_board_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_board_filter_exceptions_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board_filter_exceptions'))
    )
    op.create_index('ix_board_filter_exceptions_board_id', 'board_filter_exceptions', ['board_id'], unique=False)
    op.create_index('ix_board_filter_exceptions_user_id_board_id', 'board_filter_exceptions', ['user_id', 'board_id'], unique=False)
    op.add_column('board_jobs', sa.Column('workplace', sa.Text(), server_default='unknown', nullable=False))
    op.add_column('board_jobs', sa.Column('workplace_label', sa.Text(), nullable=True))
    op.add_column('board_jobs', sa.Column('locations', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False))
    op.create_check_constraint(op.f('ck_board_jobs_workplace'), 'board_jobs', "workplace in ('remote','hybrid','onsite','unknown')")
    op.add_column('watched_boards', sa.Column('include_unstated_workplace', sa.Boolean(), nullable=True))


def downgrade() -> None:
    op.drop_column('watched_boards', 'include_unstated_workplace')
    op.drop_constraint(op.f('ck_board_jobs_workplace'), 'board_jobs', type_='check')
    op.drop_column('board_jobs', 'locations')
    op.drop_column('board_jobs', 'workplace_label')
    op.drop_column('board_jobs', 'workplace')
    op.drop_index('ix_board_filter_exceptions_user_id_board_id', table_name='board_filter_exceptions')
    op.drop_index('ix_board_filter_exceptions_board_id', table_name='board_filter_exceptions')
    op.drop_table('board_filter_exceptions')
    op.drop_table('job_filters')
